### ISSUE TITLE
Feature: User can search for a restaurant

### ISSUE THREAD

**Issue by andychen97** [andychen97/final-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can search for a restaurant based on location and keyword

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

A user would type in a keyword (ex: pizza) and a location (ex:Irvine or 92618) which would populate the page with results

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-07-25 at 4 50 28 PM](https://user-images.githubusercontent.com/100327736/180893619-fc22ca85-8948-406f-908a-b862625b5cc6.png)
![Screen Shot 2022-07-25 at 4 50 35 PM](https://user-images.githubusercontent.com/100327736/180893634-2e580c99-294f-460f-8871-2bf9515a0a61.png)

## ✅ Task Lists
> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] 'fetch' data with GET request using searched keyword/location to the yelp's api
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks
- [x] Create a component for the header
- [x] Create a component for the hero image/search feature
- [x] add an onClick event listener for the form

### 🧑‍⚕️ Clean Up Tasks
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented-out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
