### ISSUE TITLE
Feature: User can view a list of restaurant

### ISSUE THREAD

**Issue by andychen97** [andychen97/final-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can view a list of restaurants.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

After searching, users will be able to see the results of their search.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-07-23 at 5 54 17 PM](https://user-images.githubusercontent.com/100327736/180627756-2f5092c0-0b5d-4d05-953c-e6e72cbf0f75.png)
![Screen Shot 2022-07-25 at 4 32 47 PM](https://user-images.githubusercontent.com/100327736/180891909-63954712-0b49-44da-8da3-04936b947c0f.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] refactor code to fetch API after redirecting page
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a component for a single result
- [x] Create results page
- [x] redirect page
- [x] pass props to the results page to render full results

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
